export class ConsultaDocumentosElectronicosDTO{
  item!:string;
  nroAuxiliar!:string;
  tipoDocumento!:string;
  serie!:string;
  numero!:string;
  nroDocumentoProveedor!:string;
  razonSocialProveedor!:string
  fechaEmision!:Date
  fechaContable!:Date
  moneda!:string
  base!:number
  exonerado!:number
  igv!:number
  total!:number
  estado!:string
   idDatoSunat!:string;
   idSunatEstadoDocumento!:string;
   idSunatEstadoProveedor!:string;
   idSunatEstadoDomicilioProveedor!:string;
   idDocumento!:string;
   glsRuc!:string;
   idRegistroCompra!:string;
   totalPrecioCompra!:number;
   glsSunatEstadoDocumento!:string
   glsSunatEstadoProveedor!:string
   glsSunatEstadoDomicilioProveedor!:string
   glsSunatObservacionesDocumento!:string
   abreDocumento!:string
}

